# Generated by Django 3.0.5 on 2020-05-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Reviewed'), ('N', 'Not reviewed'), ('E', 'Error')], default='R', max_length=1),
            preserve_default=False,
        ),
    ]
