# Generated by Django 3.0.5 on 2020-05-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_website_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('N', 'Not reviewed'), ('R', 'Reviewed'), ('E', 'Error'), ('A', 'Accepted')], max_length=1),
        ),
    ]
