# Generated by Django 3.0.5 on 2020-05-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200523_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('E', 'Error'), ('R', 'Reviewed'), ('N', 'Not reviewed'), ('A', 'Accepted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
