# Generated by Django 3.0.5 on 2020-05-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200523_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'the ox',
                'verbose_name_plural': 'the oxen',
                'db_table': 'ox',
            },
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['rating'], 'verbose_name': 'the website', 'verbose_name_plural': 'the websites'},
        ),
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('E', 'Error'), ('R', 'Reviewed'), ('A', 'Accepted'), ('N', 'Not reviewed')], max_length=1),
        ),
        migrations.AlterModelTable(
            name='website',
            table='website_custom_table_name',
        ),
    ]
