# Generated by Django 3.0.5 on 2020-05-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200523_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('N', 'Not reviewed'), ('R', 'Reviewed'), ('A', 'Accepted'), ('E', 'Error')], max_length=1),
        ),
    ]
